### ISSUE TITLE
some notes (bug & idea)

### ISSUE THREAD

**Issue by zghwi** [frissyn/dstrap.cr#1]
hi frissyn, its zplusfour
I just found a bug, and I wanna give you some idea :)

### Bug:

look here:
![image](https://user-images.githubusercontent.com/73612690/118152193-1b4cc780-b41d-11eb-93b4-17e3bac45a3f.png)

this is a directory, and it has a file icon, can you please fix that?

### Idea:

the idea is: use the `ARGV` variable, the `ARGV` variable is the cli (crystal executable) 's arguments, it has the Array type
like for example create a function that lists the files in a dir:

```cr
def list_dir(__dirname)
  # do something...
end
```

and then use the `ARGV` variable to list the dir:

```cr
# idk how to calculate the array length in Crystal (is it like ruby? .length() ?)
if ARGV.length() == 0 do
  list_dir('.')
else
  list_dir(ARGV[0])
end

# I hope you understand the code :)
```

this is better than only listing the parent and the current directory.
however, ima try to create a pull request to make these changes, idk bc idk how to calculate the length of an array lol :D

but anyway, good job on this project :)

**Comment by frissyn** [comment]
For some reason, the parent directory lists the current directory as a file, which is a bug with Crystal's `File` class, not my code. I'll include a check for that and omit it from the parent directory contents.

As for the CLI stuff, I wanted `dstrap` to be as light as possible, being a supplement to `ls -a`. I intend to add some flag options, like `--no-color` and `-c` to list the current directory contents only. As for listing other stuff, there could be a `dirname` argument for looking at the contents of a directory you're not in. 

Like I said though, `dstrap` should be extremely light, and allow for informational output without the use of excessive arguments or options.

Thanks for the issue, I'll work on this soon 👍🏽

**Comment by zghwi** [comment]
Oh, thanks for the explanation!
I thought it'd be cool if you use the cli arguments, but it's ok, it was just an idea :)
Oh and just a quick question... why did you choose Crystal? instead of Python or JavaScript, or any other language?
So you'll have fewer errors or bugs...

**Comment by frissyn** [comment]
I wanted a static language with an easy-to-use interface for files and directories. Crystal fit that pretty well. I had a working prototype in pure Bash, but I'm not that good with shell script. =P

**Comment by zghwi** [comment]
Oh ok

**Comment by zghwi** [comment]
![image](https://user-images.githubusercontent.com/73612690/118331735-aa3b0c00-b511-11eb-886a-e253d368cf25.png)

you could do something, when a folder is empty, instead of listing no files, write `no files or directories`
:)
